### ISSUE TITLE
make error on gnuradio 3.8.1.0

### ISSUE THREAD

**Issue by alexxmarsh44** [kit-cel/gr-radar#40]
This code is no longer working with GNUradio 3.8.1.0.  There is an error in cmake requiring 3.7.2 but I changed the cmake file to 3.8.1.0.  It then cmake's successfully and the make command gets to 89% built and then I receive this error:

[ 89%] Linking CXX executable test-radar
/usr/bin/ld: libgnuradio-radar.so: undefined reference to `gr::sync_block::forecast(int, std::vector<int, std::allocator<int> >&)'
/usr/bin/ld: libgnuradio-radar.so: undefined reference to `gr::block::fixed_rate_noutput_to_ninput(int)'
/usr/bin/ld: libgnuradio-radar.so: undefined reference to `gr::sync_block::general_work(int, std::vector<int, std::allocator<int> >&, std::vector<void const*, std::allocator<void const*> >&, std::vector<void*, std::allocator<void*> >&)'
/usr/bin/ld: libgnuradio-radar.so: undefined reference to `gr::block::unset_processor_affinity()'
/usr/bin/ld: libgnuradio-radar.so: undefined reference to `log4cpp::Appender::AppenderMapStorageInitializer::~AppenderMapStorageInitializer()'
/usr/bin/ld: libgnuradio-radar.so: undefined reference to `pmt::get_PMT_F()'
/usr/bin/ld: libgnuradio-radar.so: undefined reference to `vtable for gr::tagged_stream_block'
/usr/bin/ld: libgnuradio-radar.so: undefined reference to `gr::basic_block::message_port_register_in(boost::shared_ptr<pmt::pmt_base>)'
/usr/bin/ld: libgnuradio-radar.so: undefined reference to `gr::block::nitems_read(unsigned int)'
/usr/bin/ld: libgnuradio-radar.so: undefined reference to `gr::sync_block::sync_block(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, boost::shared_ptr<gr::io_signature>, boost::shared_ptr<gr::io_signature>)'
/usr/bin/ld: libgnuradio-radar.so: undefined reference to `gr::tagged_stream_block::parse_length_tags(std::vector<std::vector<gr::tag_t, std::allocator<gr::tag_t> >, std::allocator<std::vector<gr::tag_t, std::allocator<gr::tag_t> > > > const&, std::vector<int, std::allocator<int> >&)'
/usr/bin/ld: libgnuradio-radar.so: undefined reference to `gr::io_signature::make(int, int, int)'
/usr/bin/ld: libgnuradio-radar.so: undefined reference to `gr::tagged_stream_block::calculate_output_stream_length(std::vector<int, std::allocator<int> > const&)'
/usr/bin/ld: libgnuradio-radar.so: undefined reference to `pmt::symbol_to_string[abi:cxx11](boost::shared_ptr<pmt::pmt_base> const&)'
/usr/bin/ld: libgnuradio-radar.so: undefined reference to `gr::block::log_level[abi:cxx11]()'
/usr/bin/ld: libgnuradio-radar.so: undefined reference to `pmt::from_long(long)'
/usr/bin/ld: libgnuradio-radar.so: undefined reference to `pmt::from_double(double)'
/usr/bin/ld: libgnuradio-radar.so: undefined reference to `pmt::dict_has_key(boost::shared_ptr<pmt::pmt_base> const&, boost::shared_ptr<pmt::pmt_base> const&)'
/usr/bin/ld: libgnuradio-radar.so: undefined reference to `gr::tagged_stream_block::update_length_tags(int, int)'
/usr/bin/ld: libgnuradio-radar.so: undefined reference to `gr::block::get_tags_in_range(std::vector<gr::tag_t, std::allocator<gr::tag_t> >&, unsigned int, unsigned long, unsigned long, boost::shared_ptr<pmt::pmt_base> const&)'
/usr/bin/ld: libgnuradio-radar.so: undefined reference to `pmt::nth(unsigned long, boost::shared_ptr<pmt::pmt_base>)'
/usr/bin/ld: libgnuradio-radar.so: undefined reference to `pmt::list2(boost::shared_ptr<pmt::pmt_base> const&, boost::shared_ptr<pmt::pmt_base> const&)'
/usr/bin/ld: libgnuradio-radar.so: undefined reference to `pmt::tuple_ref(boost::shared_ptr<pmt::pmt_base> const&, unsigned long)'
/usr/bin/ld: libgnuradio-radar.so: undefined reference to `pmt::get_PMT_NIL()'
/usr/bin/ld: libgnuradio-radar.so: undefined reference to `gr::block::start()'
/usr/bin/ld: libgnuradio-radar.so: undefined reference to `gr::tagged_stream_block::tagged_stream_block(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, boost::shared_ptr<gr::io_signature>, boost::shared_ptr<gr::io_signature>, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
/usr/bin/ld: libgnuradio-radar.so: undefined reference to `volk_32fc_x2_multiply_32fc'
/usr/bin/ld: libgnuradio-radar.so: undefined reference to `pmt::to_double(boost::shared_ptr<pmt::pmt_base>)'
/usr/bin/ld: libgnuradio-radar.so: undefined reference to `pmt::f32vector_elements(boost::shared_ptr<pmt::pmt_base>)'
/usr/bin/ld: libgnuradio-radar.so: undefined reference to `volk_32f_x2_dot_prod_32f'
/usr/bin/ld: libgnuradio-radar.so: undefined reference to `pmt::list4(boost::shared_ptr<pmt::pmt_base> const&, boost::shared_ptr<pmt::pmt_base> const&, boost::shared_ptr<pmt::pmt_base> const&, boost::shared_ptr<pmt::pmt_base> const&)'
/usr/bin/ld: libgnuradio-radar.so: undefined reference to `gr::sync_block::fixed_rate_noutput_to_ninput(int)'
/usr/bin/ld: libgnuradio-radar.so: undefined reference to `gr::block::block(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, boost::shared_ptr<gr::io_signature>, boost::shared_ptr<gr::io_signature>)'
/usr/bin/ld: libgnuradio-radar.so: undefined reference to `pmt::from_uint64(unsigned long)'
/usr/bin/ld: libgnuradio-radar.so: undefined reference to `pmt::list3(boost::shared_ptr<pmt::pmt_base> const&, boost::shared_ptr<pmt::pmt_base> const&, boost::shared_ptr<pmt::pmt_base> const&)'
/usr/bin/ld: libgnuradio-radar.so: undefined reference to `pmt::length(boost::shared_ptr<pmt::pmt_base> const&)'
/usr/bin/ld: libgnuradio-radar.so: undefined reference to `pmt::f32vector_elements(boost::shared_ptr<pmt::pmt_base>, unsigned long&)'
/usr/bin/ld: libgnuradio-radar.so: undefined reference to `gr::block::fixed_rate_ninput_to_noutput(int)'
/usr/bin/ld: libgnuradio-radar.so: undefined reference to `gr::block::nitems_written(unsigned int)'
/usr/bin/ld: libgnuradio-radar.so: undefined reference to `pmt::to_long(boost::shared_ptr<pmt::pmt_base>)'
/usr/bin/ld: libgnuradio-radar.so: undefined reference to `gr::block::general_work(int, std::vector<int, std::allocator<int> >&, std::vector<void const*, std::allocator<void const*> >&, std::vector<void*, std::allocator<void*> >&)'
/usr/bin/ld: libgnuradio-radar.so: undefined reference to `gr::block::set_tag_propagation_policy(gr::block::tag_propagation_policy_t)'
/usr/bin/ld: libgnuradio-radar.so: undefined reference to `gr::msg_accepter::post(boost::shared_ptr<pmt::pmt_base>, boost::shared_ptr<pmt::pmt_base>)'
/usr/bin/ld: libgnuradio-radar.so: undefined reference to `gr::block::stop()'
/usr/bin/ld: libgnuradio-radar.so: undefined reference to `pmt::is_tuple(boost::shared_ptr<pmt::pmt_base>)'
/usr/bin/ld: libgnuradio-radar.so: undefined reference to `pmt::init_f32vector(unsigned long, std::vector<float, std::allocator<float> > const&)'
/usr/bin/ld: libgnuradio-radar.so: undefined reference to `pmt::eqv(boost::shared_ptr<pmt::pmt_base> const&, boost::shared_ptr<pmt::pmt_base> const&)'
/usr/bin/ld: libgnuradio-radar.so: undefined reference to `typeinfo for gr::sync_block'
/usr/bin/ld: libgnuradio-radar.so: undefined reference to `pmt::is_integer(boost::shared_ptr<pmt::pmt_base>)'
/usr/bin/ld: libgnuradio-radar.so: undefined reference to `log4cpp::Appender::AppenderMapStorageInitializer::AppenderMapStorageInitializer()'
/usr/bin/ld: libgnuradio-radar.so: undefined reference to `gr::block::add_item_tag(unsigned int, gr::tag_t const&)'
/usr/bin/ld: libgnuradio-radar.so: undefined reference to `pmt::is_f32vector(boost::shared_ptr<pmt::pmt_base>)'
/usr/bin/ld: libgnuradio-radar.so: undefined reference to `gr::block::get_tags_in_range(std::vector<gr::tag_t, std::allocator<gr::tag_t> >&, unsigned int, unsigned long, unsigned long)'
/usr/bin/ld: libgnuradio-radar.so: undefined reference to `gr::tagged_stream_block::forecast(int, std::vector<int, std::allocator<int> >&)'
/usr/bin/ld: libgnuradio-radar.so: undefined reference to `gr::basic_block::message_port_pub(boost::shared_ptr<pmt::pmt_base>, boost::shared_ptr<pmt::pmt_base>)'
/usr/bin/ld: libgnuradio-radar.so: undefined reference to `gnuradio::detail::sptr_magic::fetch_initial_sptr(gr::basic_block*)'
/usr/bin/ld: libgnuradio-radar.so: undefined reference to `pmt::to_uint64(boost::shared_ptr<pmt::pmt_base>)'
/usr/bin/ld: libgnuradio-radar.so: undefined reference to `gr::block::~block()'
/usr/bin/ld: libgnuradio-radar.so: undefined reference to `vtable for gr::sync_block'
/usr/bin/ld: libgnuradio-radar.so: undefined reference to `typeinfo for gr::basic_block'
/usr/bin/ld: libgnuradio-radar.so: undefined reference to `gr::sync_block::fixed_rate_ninput_to_noutput(int)'
/usr/bin/ld: libgnuradio-radar.so: undefined reference to `typeinfo for gr::tagged_stream_block'
/usr/bin/ld: libgnuradio-radar.so: undefined reference to `typeinfo for gr::block'
/usr/bin/ld: libgnuradio-radar.so: undefined reference to `pmt::list_add(boost::shared_ptr<pmt::pmt_base>, boost::shared_ptr<pmt::pmt_base> const&)'
/usr/bin/ld: libgnuradio-radar.so: undefined reference to `gr::basic_block::message_port_register_out(boost::shared_ptr<pmt::pmt_base>)'
/usr/bin/ld: libgnuradio-radar.so: undefined reference to `gr::tagged_stream_block::check_topology(int, int)'
/usr/bin/ld: libgnuradio-radar.so: undefined reference to `gr::block::forecast(int, std::vector<int, std::allocator<int> >&)'
/usr/bin/ld: libgnuradio-radar.so: undefined reference to `gr::block::set_processor_affinity(std::vector<int, std::allocator<int> > const&)'
/usr/bin/ld: libgnuradio-radar.so: undefined reference to `gr::block::set_log_level(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)'
/usr/bin/ld: libgnuradio-radar.so: undefined reference to `gr::tagged_stream_block::general_work(int, std::vector<int, std::allocator<int> >&, std::vector<void const*, std::allocator<void const*> >&, std::vector<void*, std::allocator<void*> >&)'
/usr/bin/ld: libgnuradio-radar.so: undefined reference to `pmt::list1(boost::shared_ptr<pmt::pmt_base> const&)'
/usr/bin/ld: libgnuradio-radar.so: undefined reference to `pmt::string_to_symbol(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
/usr/bin/ld: libgnuradio-radar.so: undefined reference to `pmt::make_tuple(boost::shared_ptr<pmt::pmt_base> const&, boost::shared_ptr<pmt::pmt_base> const&)'
collect2: error: ld returned 1 exit status
make[2]: *** [lib/CMakeFiles/test-radar.dir/build.make:142: lib/test-radar] Error 1
make[1]: *** [CMakeFiles/Makefile2:287: lib/CMakeFiles/test-radar.dir/all] Error 2
make: *** [Makefile:160: all] Error 2

Is there any workaround to get it to make?  Thanks.

**Comment by sbmueller** [comment]
This code does not work with 3.8. Have a look at #36 .

**Comment by marcusmueller** [comment]
Should be solved through #41, so I'm closing this for now. If the problem persists: Please do reopen this!
